# Generated by Django 5.0 on 2026-03-02 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0005_alter_visit_options_alter_client_client_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='visits.clienttype', verbose_name='Type'),
        ),
    ]
