# Generated by Django 5.0 on 2026-03-05 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0006_alter_client_client_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttype',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True, verbose_name='Abbreviation'),
        ),
    ]
