# Generated by Django 5.0 on 2026-02-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business_Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('time_zone', models.CharField(max_length=100)),
                ('locale', models.CharField(max_length=100)),
                ('distance_unit', models.CharField(max_length=100)),
                ('max_valid_distance', models.IntegerField()),
                ('min_time_between_visits', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo_url', models.CharField(max_length=100)),
            ],
        ),
    ]
