# Generated by Django 5.0 on 2026-02-26 19:18

from django.db import migrations


def create_default_config(apps, schema_editor):
    Business_Config = apps.get_model('core', 'Business_Config')
    if not Business_Config.objects.exists():
        Business_Config.objects.create(
            business_name="EchoRoute Business",
            time_zone="UTC",
            locale="en-US",
            distance_unit="km",
            max_valid_distance=100,
            min_time_between_visits=30,
            logo_url="DEFAULT_LOGO"
        )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_config),
    ]
