# Generated by Django 5.0 on 2026-03-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_default_business_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_config',
            name='distance_unit',
            field=models.CharField(choices=[('m', 'Meters'), ('ft', 'Feet')], default='m', max_length=100),
        ),
        migrations.AlterField(
            model_name='business_config',
            name='logo_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='business_config',
            name='max_valid_distance',
            field=models.IntegerField(default=100, help_text='Maximum valid distance in meters'),
        ),
        migrations.AlterField(
            model_name='business_config',
            name='min_time_between_visits',
            field=models.IntegerField(default=10, help_text='Minimum time between visits in minutes'),
        ),
    ]
