# Generated by Django 5.0 on 2026-03-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_business_config_distance_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_config',
            name='logo_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
