# Generated by Django 5.0 on 2026-03-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_business_config_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_config',
            name='distance_unit',
            field=models.CharField(choices=[('m', 'International'), ('ft', 'Imperial')], default='m', max_length=100),
        ),
        migrations.AlterField(
            model_name='business_config',
            name='locale',
            field=models.CharField(choices=[('es-MX', 'Spanish (Mexico)'), ('en-ca', 'English (Canada)')], default='es-MX', max_length=100),
        ),
        migrations.AlterField(
            model_name='business_config',
            name='time_zone',
            field=models.CharField(default='America/Mexico_City', max_length=100),
        ),
    ]
