# Generated by Django 5.0 on 2026-03-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_business_config_distance_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_config',
            name='locale',
            field=models.CharField(choices=[('es-419', 'Spanish (Latin America)'), ('en-ca', 'English (Canada)')], default='es-MX', max_length=100),
        ),
    ]
